services:
  db:
    build:
        context: ./schemas
    expose:
      - "${DB_PORT}"
    environment:
      MYSQL_USER: 'hfh'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_ROOT_HOST: '%'

    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:6-alpine
    expose:
      - "${REDIS_PORT}"
    env_file:
      - .env

  backend:
    build:
        context: .
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: redis
      DB_HOST: db 
      DB_USER: 'hfh'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_ROOT_PASSWORD: '${DB_PASSWORD}'
      DB_NAME: '${DB_NAME}'
      MYSQL_ROOT_HOST: '%'
    env_file:
      - .env

volumes:
    backend_data:
    db_data:

version: "3.0"
